
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prabhat-PC
 */
public class equation_calculator1 extends javax.swing.JFrame {

    /**
     * Creates new form equation_calculator1
     */
    public equation_calculator1() {
        initComponents();
        x1.setVisible(false);
        x2.setVisible(false);
        m.setVisible(false);
        one.setVisible(false);
        two.setVisible(false);
   CON.setVisible(false);
   A.setVisible(false);
   B.setVisible(false);
   C.setVisible(false);
   a.setVisible(false);
   b.setVisible(false);
   c.setVisible(false);
   r.setVisible(false);
   re.setVisible(false);
   
    }
 
    private void num(int a,int b,int c)
    { x1.setVisible(true);
        x2.setVisible(true);
        m.setVisible(true);
        one.setVisible(true);
        two.setVisible(true);
        double temp=Math.sqrt((b*b)-(4*a*c));
        double x=(-b+temp)/(2*a);
        double y=(-b-temp)/(2*a);
        x1.setText(String.valueOf(x));
        x2.setText(String.valueOf(y));
   
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        h = new javax.swing.JButton();
        g = new javax.swing.JButton();
        CON = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        one = new javax.swing.JLabel();
        two = new javax.swing.JLabel();
        x1 = new javax.swing.JTextField();
        x2 = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        r = new javax.swing.JButton();
        re = new javax.swing.JButton();
        POW = new javax.swing.JLabel();
        POW1 = new javax.swing.JTextField();
        E = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        h.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h.setText("HOME");
        h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hMousePressed(evt);
            }
        });

        g.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        g.setText("GO BACK");
        g.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gMousePressed(evt);
            }
        });

        CON.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CON.setText("CONSTANTS");

        m.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        m.setText("ROOTS");

        A.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        A.setText("A");

        B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B.setText("B");

        C.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        C.setText("C");

        one.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        one.setText("X1");

        two.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        two.setText("X2");

        r.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        r.setText("ROOTS");
        r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActionPerformed(evt);
            }
        });

        re.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        re.setText("RESET");
        re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reActionPerformed(evt);
            }
        });

        POW.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        POW.setText("POWER 2 OR 3");

        E.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        E.setText("EQUATION");
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(h)
                .addGap(103, 103, 103)
                .addComponent(POW)
                .addGap(18, 18, 18)
                .addComponent(POW1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(g)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(CON))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(A)
                                    .addComponent(B))
                                .addGap(59, 59, 59))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(C)
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(c, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(a, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b, javax.swing.GroupLayout.Alignment.LEADING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(one)
                            .addComponent(two))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(x1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(x2))))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(r)
                        .addGap(79, 79, 79)
                        .addComponent(re))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(E)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(h)
                    .addComponent(g)
                    .addComponent(POW)
                    .addComponent(POW1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CON)
                    .addComponent(m))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(one)
                    .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(B)
                            .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(two))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(E)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r)
                    .addComponent(re))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rActionPerformed
  String s1=a.getText();
  String s2=b.getText();
String s3=c.getText();int p=0,q=0,t=0;
if((Character.isDigit(s1.charAt(0))||Character.isDigit(s1.charAt(1)))&&(Character.isDigit(s2.charAt(0))||Character.isDigit(s2.charAt(1)))&&(Character.isDigit(s3.charAt(0))||Character.isDigit(s3.charAt(1))))
{
    if(s1.charAt(0)=='-')
  p=Integer.parseInt(s1.substring(1));
  if(s2.charAt(0)=='-')
  q=Integer.parseInt(s2.substring(1));
  if(s3.charAt(0)=='-')
  t=Integer.parseInt(s3.substring(1)); 
  else
  {    p=Integer.parseInt(s1);
  q=Integer.parseInt(s2);
  t=Integer.parseInt(s3);}
  
num(p,q,t);

}
else
{a.setText("");
b.setText("");
c.setText("");
JOptionPane.showMessageDialog(null,"enter a valid number","just numbers",JOptionPane.INFORMATION_MESSAGE);
      a.requestFocus();
      b.requestFocus();c.requestFocus();
}
// TODO add your handling code here:
    }//GEN-LAST:event_rActionPerformed

    private void reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reActionPerformed
      x1.setVisible(false);
        x2.setVisible(false);
        m.setVisible(false);
        one.setVisible(false);
        two.setVisible(false); 
        a.setText("");
b.setText("");
c.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_reActionPerformed

    private void gMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gMousePressed
      mycalculator frame2=new mycalculator();
      equation_calculator1.this.setVisible(false);
      frame2.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_gMousePressed

    private void hMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hMousePressed
       MATH frame2=new MATH();
      equation_calculator1.this.setVisible(false);
      frame2.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_hMousePressed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
if(Integer.parseInt(POW1.getText())==2)
        {
        POW.setVisible(false);
        POW1.setVisible(false);
        E.setVisible(false);
         CON.setVisible(true);
   A.setVisible(true);
   B.setVisible(true);
   C.setVisible(true);
   a.setVisible(true);
   b.setVisible(true);
   c.setVisible(true);
   r.setVisible(true);
   re.setVisible(true);}
if(Integer.parseInt(POW1.getText())==3)
{ POW.setVisible(false);
        POW1.setVisible(false);
        E.setVisible(false);
        equation_calculator frame=new equation_calculator();
        equation_calculator1.this.setVisible(false);
        frame.setVisible(true);
        
    
}
else
{ JOptionPane.showMessageDialog(null,"enter a valid number","just numbers",JOptionPane.INFORMATION_MESSAGE);
POW.requestFocus();
POW1.setText("");
}// TODO add your handling code here:
    }//GEN-LAST:event_EActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(equation_calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(equation_calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(equation_calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(equation_calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new equation_calculator1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JLabel C;
    private javax.swing.JLabel CON;
    private javax.swing.JButton E;
    private javax.swing.JLabel POW;
    private javax.swing.JTextField POW1;
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JLabel m;
    private javax.swing.JLabel one;
    private javax.swing.JButton r;
    private javax.swing.JButton re;
    private javax.swing.JLabel two;
    private javax.swing.JTextField x1;
    private javax.swing.JTextField x2;
    // End of variables declaration//GEN-END:variables
}
