
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prabhat-PC
 */
public class equation_calculator extends javax.swing.JFrame {

    /**
     * Creates new form equation_calculator
     */
    public equation_calculator() {
        initComponents();
   one.setVisible(false);
   two.setVisible(false);
   three.setVisible(false);
   four.setVisible(false);
   E.setVisible(false);  
   F.setVisible(false);
   G.setVisible(false);
}
private void num(int a,int b,int c,int d)
{one.setVisible(true);
   two.setVisible(true);
   three.setVisible(true);
   four.setVisible(true);
   E.setVisible(true);  
   F.setVisible(true);
   G.setVisible(true);
    try{
    double e,f,g,h,i,j,k,l,m,n,p,r,s,t,u,x1,x2,x3;
int w=0;
     e=2.7182818284590;
        f=((3*c/a)-(b*b/(a*a)))/3;
        g=((2*b*b*b/(a*a*a))-(9*b*c/(a*a))+(27*d/a))/27;
        h=(g*g/4)+(f*f*f/27);
        i=Math.sqrt(((g*g/4)-h));
        j=Math.exp(Math.log10(i)/Math.log10(e)/3);
        k=Math.acos((-1)*(g/(2*i)));
        l=j*(-1);
        m=Math.cos(k/3);
        n=Math.sqrt(3)*Math.sin(k/3);
        p=(b/3*a)*(-1);
        r=(-1)*(g/2)+Math.sqrt(h);
        s=Math.exp(Math.log10(r)/Math.log10(e)/3);
        t=(-1)*(g/2)-Math.sqrt(h);
        u=Math.exp(Math.log10(t)/Math.log10(e)/3);
        if(h>0)
        w=1;
        if(h<0)
        w=3;
        if((f==0)&&(g==0)&&(h==0))
        w=2;
        int y=w;
        switch(y)
        {
            case 1:
            {
            x1=(s+u)-(b/3*a);
            x2=(-1)*(s+u)/2-(b/3*a);
            x3=(s-u)*Math.sqrt(3)/2;
            E.setText(String.valueOf(Math.ceil(x1)));
            F.setText(Math.ceil(x2)+"+i"+Math.ceil(x3));
            G.setText(Math.ceil(x2)+"-i"+Math.ceil(x3));
            break;
            }
        case 2:
        {
            x1=Math.exp(Math.log10(d/a)/Math.log10(e)/3)*(-1);
            E.setText(String.valueOf(Math.ceil(x1)));
            F.setText(String.valueOf(Math.ceil(x1)));
            G.setText(String.valueOf(Math.ceil(x1)));
            break;
        }
        case 3:
        {
            x1=2*j*Math.cos(k/3)-(b/3*a);
            x2=l*(m+n)+p;
            x3=l*(m-n)+p;
            E.setText(String.valueOf(Math.ceil(x1)));
            F.setText(String.valueOf(Math.ceil(x2)));
            G.setText(String.valueOf(Math.ceil(x3)));
            break;
        }
    }}
    catch(Exception e)
    {E.setText("u may try again");}
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        A = new javax.swing.JTextField();
        B = new javax.swing.JTextField();
        D = new javax.swing.JTextField();
        C = new javax.swing.JTextField();
        one = new javax.swing.JLabel();
        two = new javax.swing.JLabel();
        three = new javax.swing.JLabel();
        four = new javax.swing.JLabel();
        E = new javax.swing.JTextField();
        G = new javax.swing.JTextField();
        F = new javax.swing.JTextField();
        ROOTS = new javax.swing.JButton();
        R = new javax.swing.JButton();
        H = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("constants");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("a");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("b");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("c");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("d");

        one.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        one.setText("Roots");

        two.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        two.setText("X1");

        three.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        three.setText("X2");

        four.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        four.setText("X3");

        ROOTS.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ROOTS.setText("ROOTS");
        ROOTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ROOTSActionPerformed(evt);
            }
        });

        R.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        R.setText("RESET");
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RActionPerformed(evt);
            }
        });

        H.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        H.setText("HOME");
        H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HMouseEntered(evt);
            }
        });
        H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HActionPerformed(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        EXIT.setText(" GO BACK");
        EXIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EXITMouseEntered(evt);
            }
        });
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(H)
                        .addGap(447, 447, 447)
                        .addComponent(EXIT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)
                        .addGap(253, 253, 253)
                        .addComponent(one))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(37, 37, 37)
                                .addComponent(ROOTS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(36, 36, 36)
                                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(191, 191, 191)
                                    .addComponent(two)
                                    .addGap(42, 42, 42)
                                    .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4))
                                            .addGap(37, 37, 37)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(C, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                .addComponent(B)))
                                        .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(191, 191, 191)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(three)
                                        .addComponent(four))
                                    .addGap(42, 42, 42)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(H))
                    .addComponent(EXIT))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(two))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(three))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(four)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ROOTS)
                    .addComponent(R))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ROOTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ROOTSActionPerformed
       String s=A.getText();
       String s1=B.getText();
       String s2=C.getText();
       String s3=D.getText();
       if((Character.isDigit(s.charAt(0))||Character.isDigit(s.charAt(1)))&&(Character.isDigit(s1.charAt(0))||Character.isDigit(s1.charAt(1)))&&(Character.isDigit(s2.charAt(0))||Character.isDigit(s2.charAt(1)))&&(Character.isDigit(s3.charAt(0))||Character.isDigit(s3.charAt(1))))
       {
           int p=0,q=0,r=0,t=0;
            if(s.charAt(0)=='-')
  p=Integer.parseInt(s.substring(1));
  if(s1.charAt(0)=='-')
  q=Integer.parseInt(s1.substring(1));
  if(s2.charAt(0)=='-')
  r=Integer.parseInt(s2.substring(1));
  if(s3.charAt(0)=='-')
      t=Integer.parseInt(s3.substring(1));
  else
  {   p=Integer.parseInt(s);
      q=Integer.parseInt(s1);
  r=Integer.parseInt(s2);
  t=Integer.parseInt(s3);}
           num(p,q,r,t);}
       else
       {
           A.setText("");
           B.setText("");
           C.setText("");
           D.setText("");
           JOptionPane.showMessageDialog(null,"enter a valid number","just numbers",JOptionPane.INFORMATION_MESSAGE);
      A.requestFocus();
      B.requestFocus();C.requestFocus();D.requestFocus();
       }
    }//GEN-LAST:event_ROOTSActionPerformed

    private void RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RActionPerformed
     A.setText("");
           B.setText("");
           C.setText("");
           D.setText(""); 
         one.setVisible(false);
   two.setVisible(false);
   three.setVisible(false);
   four.setVisible(false);
   E.setVisible(false);  
   F.setVisible(false);
   G.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_RActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_EXITActionPerformed

    private void HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_HActionPerformed

    private void HMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HMouseEntered
      MATH frame2=new MATH();
       equation_calculator.this.setVisible(false);
       frame2.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_HMouseEntered

    private void EXITMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITMouseEntered
       mycalculator frame2=new mycalculator();
       equation_calculator.this.setVisible(false);
       frame2.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_EXITMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(equation_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(equation_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(equation_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(equation_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new equation_calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField B;
    private javax.swing.JTextField C;
    private javax.swing.JTextField D;
    private javax.swing.JTextField E;
    private javax.swing.JButton EXIT;
    private javax.swing.JTextField F;
    private javax.swing.JTextField G;
    private javax.swing.JButton H;
    private javax.swing.JButton R;
    private javax.swing.JButton ROOTS;
    private javax.swing.JLabel four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel one;
    private javax.swing.JLabel three;
    private javax.swing.JLabel two;
    // End of variables declaration//GEN-END:variables
}
