/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prabhat-PC
 */
public class Maths_formulas3 extends javax.swing.JFrame {

    /**
     * Creates new form Maths_formulas3
     */
    public Maths_formulas3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("<html><body><h1><font color=\"blue\">TRIGONOMETRIC IDENTITIES AND FORMULAS</FONT>\n</H1><table border=\"2\" cell spacing=\"25\" cell padding=\"25\" align=\"center\"><tr><td colspan=\"2\"><font color=\"blue\"><center>Product to sum formulas</center></font></td></tr>\n<tr><td>sinu sinv=1/<sub>2</sub>[cos(u-v)-cos(u+v)]</td><td>cosu cosv=1/<sub>2</sub>[cos(u+v)+cos(u-v)]</td></tr><tr><td>sinu cosv=1/<sub>2</sub>[sin(u+v)+sin(u-v)]</td><td>cosu sinv=1/<sub>2</sub>[sin(u+v)-sin(u-v)]</td></tr>\n<tr><td colspan=\"2\"><font color=\"blue\"><center>Sum to product formulas</center></font></td></tr>\n<tr><td>sinu+sinv=2sin(u+v)/<sub>2</sub>cos(u-v)/<sub>2</sub></td><td>sinu-sinv=2cos(u+v)/<sub>2</sub>sin(u-v)/<sub>2</sub></td></tr>\n<tr><td>cosu+cosv=2cos(u+v)/<sub>2</sub>cos(u-v)/<sub>2</sub></td><td>cosu-cosv=-2sin(u+v)/<sub>2</sub>sin(u-v)/<sub>2</sub></td></tr><tr><td colspan=\"2\"><font color=\"blue\"><center>Power reducing formulas</center></font></td></tr>\n<tr><td>sin<sup>2</sup>=(1-cos2u)/<sub>2</sub></td><td>cos<sup>2</sup>=(1+cos2u)/<sub>2<sub></td></tr><tr><td>tan<sup>2</sup>=(1-cos2u)/<sup>(1+cos2u)</sup></td></tr>\n<tr><td colspan=\"2\"><font color=\"blue\"><center>Double angle formulas</center></font></td></tr>\n<tr><td>sin(2u)=2 sinu cosu</td><td>tan(2u)=2tanu/<sub>(1-tan<sup>2</sup>u)</sub></td></tr>\n<tr><td colspan=\"2\">cos(2u)=cos<sup>2</sup>u-sin<sup>2</sup>u=2cos<sup>2</sup>u-1=1-2sin<sup>2</sup>u</td></tr><tr><td colspan=\"2\"><font color=\"blue\"><center>Sum-Difference formulas</center></font></td></tr>\n<tr><td>sin(u+<sub>-</sub>v)=sinu cosv+<sub>-</sub>cosu sinu</td><td>cos(u+<sub>-</sub>v)=cosu cosv-<sub>+</sub>sinu sinv</td></tr>\n<tr><td colspan=\"2\">tan(u+<sub>-</sub>v)=(tanu +<sub>-</sub> tanv)<sub>(1-<sub>+</sub>tanu tanv)</sub></td></tr>");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mathematics.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mathematics.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
      MATH frame2=new MATH();
      Maths_formulas3.this.setVisible(false);
frame2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
      maths_formulas frame2=new maths_formulas();
      Maths_formulas3.this.setVisible(false);
frame2.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maths_formulas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maths_formulas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maths_formulas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maths_formulas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maths_formulas3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
