/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prabhat-PC
 */
public class maths_formulas1 extends javax.swing.JFrame {

    /**
     * Creates new form maths_formulas1
     */
    public maths_formulas1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        jLabel6.setText("(a+b)^2=a^2+b^2+2ab");

        jLabel12.setText("(a+b)^2=a^2+b^2+2ab");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("GoBack");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("<html>\n<body>\n<h1><font color=\"blue\">MATHS FORMULAS</font></h1>\n<UL type=\"bullet\">\n<LI>(a+b)<sup>2</sup>=a<sup>2</sup>+b<sup>2</sup>+2ab</LI>\n<LI>(a-b)<sup>2</sup>=a<sup>2</sup>+b<sup>2</sup>-2ab</LI>\n<LI>a<sup>2</sup>+b<sup>2</sup>=(a+b)<sup>2</sup>-2ab</LI>\n<LI>a<sup>2</sup>-b<sup>2</sup>=(a-b)(a+b)</LI>\n<LI>(a<sup>2</sup>+b<sup>2</sup>+c<sup>2</sup>)=(a+b+c)<sup>2</sup>-2(ab+bc+ca)</LI><LI>(a+b+c)<sup>2</sup>=(a<sup>2</sup>+b<sup>2</sup>+c<sup>2</sup>)+2(ab+bc+ca)</LI>\n<LI>2(ab+bc+ca)=(a+b+c)<sup>2</sup>-(a<sup>2</sup>+b<sup>2</sup>+c<sup>2</sup>)</LI>\n<li>(a+b)<sup>3</sup>=a<sup>3</sup>+b<sup>3</sup>+3a<sup>2</sup>b+3ab<sup>2</sup>=a<sup>3</sup>+b<sup>3</sup>+3ab(a+b)</li>\n<li>(a-b)<sup>3</sup>=a<sup>3</sup>-b<sup>3</sup>-3a<sup>2</sup>b+3ab<sup>2</sup>=a<sup>3</sup>-b<sup>3</sup>-3ab(a-b)</li>\n<li>a<sup>3</sup>+b<sup>3</sup>=(a+b)(a<sup>2</sup>-ab+b<sup>2</sup>=(a-b)<sup>3</sup>-3a<sup>2</sup>b-3ab<sup>2</sup></li>\n<li>a<sup>3</sup>-b<sup>3</sup>=(a-b)(a<sup>2</sup>+ab+b<sup>2</sup>=(a-b)<sup>3</sup>+3a<sup>2</sup>b-3ab<sup>2</sup></li>\n<li>(a+b+b+c)<sup>3</sup>=a<sup>3</sup>+b<sup>3</sup>+c<sup>3</sup>+3(a+b)(b+c)(c+a)</li>\n<li>a<sup>3</sup>+b<sup>3</sup>+c<sup>3</sup>-3abc=(a+b+c)(a<sup>2</sup>+b<sup>2</sup>+c<sup>2</sup>-ab-bc-ca)</li>\n<li>4ab=(a+b)<sup>2</sup>-(a-b)<sup>2</sup></li><li>(x+a)(x+b)=x<sup>2</sup>+(a+b)x+ab</li><li>(x+a)(x-b)=x<sup>2</sup>+(a-b)x-ab</li><li>(x-a)(x+b)=x<sup>2</sup>+(b-a)x-ab</li><li>(x-a)(x-b)=x<sup>2</sup>-(a+b)x+ab</li>\n<li>(x+q)(x+p)(x+r)=x<sup>3</sup>+(p+q+r)x<sup>2</sup>+(pq+qr+rp)x+pqr</li><li>bc(b-c)+ca(c-a)+ab(a-b)=-(b-c)(c-a)(a-b)</li>\n<li>a<sup>2</sup>(b-c)+b<sup>2</sup>(c-a)+c<sup>2</sup>(a-b)=-(a-b)(b-c)(c-a)</li>\n<li>a(b<sup>2</sup>-c<sup>2</sup>)+b(c<sup>2</sup>-a<sup>2</sup>)+c(a<sup>2</sup>-b<sup>2</sup>)=(a-b)(b-c)(c-a)</li>\n<li>a<sup>3</sup>(b-c)+b<sup>3</sup>(c-a)+c<sup>3</sup>(a-b)=-(a-b)(b-c)(c-a)(a+b+c)</li>\n\n\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(46, 46, 46))
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
MATH frame2=new MATH();
maths_formulas1.this.setVisible(false);
frame2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  maths_formulas frame2=new maths_formulas();
  maths_formulas1.this.setVisible(false);
frame2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(maths_formulas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(maths_formulas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(maths_formulas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(maths_formulas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new maths_formulas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
