/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prabhat-PC
 */import javax.swing.JOptionPane;
public class mycalculator extends javax.swing.JFrame {

    /**
     * Creates new form mycalculator
     */
    public mycalculator() {
        initComponents();
    }
    public static final String INITIAL_VALUE_PROPERTY="2";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TWO = new javax.swing.JRadioButton();
        ONE = new javax.swing.JRadioButton();
        THREE = new javax.swing.JRadioButton();
        FOUR = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        TWO.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(TWO);
        TWO.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        TWO.setForeground(new java.awt.Color(255, 255, 255));
        TWO.setText("SCIENTIFIC CALCULATOR");
        TWO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TWOActionPerformed(evt);
            }
        });

        ONE.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(ONE);
        ONE.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        ONE.setForeground(new java.awt.Color(255, 255, 255));
        ONE.setText("CALCULATOR");
        ONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONEActionPerformed(evt);
            }
        });

        buttonGroup1.add(THREE);
        THREE.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        THREE.setForeground(new java.awt.Color(255, 255, 255));
        THREE.setText("EQUATION CALCULATOR");
        THREE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THREEActionPerformed(evt);
            }
        });

        buttonGroup1.add(FOUR);
        FOUR.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        FOUR.setForeground(new java.awt.Color(255, 255, 255));
        FOUR.setText("EXPRESSION CALCULATOR");
        FOUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOURActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FOUR)
                    .addComponent(THREE)
                    .addComponent(TWO)
                    .addComponent(ONE))
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(ONE)
                .addGap(30, 30, 30)
                .addComponent(TWO)
                .addGap(34, 34, 34)
                .addComponent(THREE)
                .addGap(29, 29, 29)
                .addComponent(FOUR)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONEActionPerformed
if(ONE.isSelected()==true)
{calculator frame2=new calculator();
mycalculator.this.setVisible(false);
frame2.setVisible(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_ONEActionPerformed

    private void TWOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TWOActionPerformed
 if(TWO.isSelected()==true)
 {calc frame=new calc();
 mycalculator.this.setVisible(false);
 frame.setVisible(true);}// TODO add your handling code here:
    }//GEN-LAST:event_TWOActionPerformed

    private void THREEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THREEActionPerformed
if(THREE.isSelected()==true)
{equation_calculator1 f=new equation_calculator1();
mycalculator.this.setVisible(false);
f.setVisible(true);
}
          // TODO add your handling code here:
    }//GEN-LAST:event_THREEActionPerformed

    private void FOURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOURActionPerformed
   if(FOUR.isSelected()==true)
   {expression_calculator f=new expression_calculator();
mycalculator.this.setVisible(false);
f.setVisible(true);
}     // TODO add your handling code here:
    }//GEN-LAST:event_FOURActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   MATH f=new MATH();
   mycalculator.this.setVisible(false);
f.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mycalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mycalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mycalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mycalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mycalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FOUR;
    private javax.swing.JRadioButton ONE;
    private javax.swing.JRadioButton THREE;
    private javax.swing.JRadioButton TWO;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
